name: Adds all issues that have 'bug' or 'feature' label to the ECRS project
on:
  issues:
    types:
      - opened
      - labeled
  workflow_dispatch:

jobs:
  add-to-ecrs-project:
    name: Add issue to ECRS project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ecrs-org/projects/1
          labeled: bug, feature
          label-operator: OR
          github-token: ${{ secrets.GITHUB_TOKEN }}

