name: Build & test (example)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'example/**'
      - '.github/workflows/build-test-example.yaml'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: example

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update toolchain
      run: rustup update
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: ${{ env.WORKING_DIR }}
      run: cargo test --verbose
