name: Build & test (example)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'examples/**'
      - '.github/workflows/build-test-example.yaml'
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-test-example-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update
      - name: Build
        run: cargo build --all-features --examples --verbose
