name: Build & test (lib)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build-test-lib.yaml'
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-test-lib-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Update toolchain
      run: rustup update
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --all-features --verbose
