name: Clippy check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'src/**'
      - '.github/workflows/clippy-check.yaml'
  workflow_dispatch:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    concurrency:
      group: clippy-check-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Update toolchain
      run: rustup update
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
